version: '3'

services:
  mysql:
    image: library/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'db'
      MYSQL_TCP_PORT: 3306
    restart: unless-stopped
